INSERT INTO CLASSROOM (trainerFName, trainerLName) VALUES ('John', 'Doe')
INSERT INTO CLASSROOM (trainerFName, trainerLName) VALUES ('Tom', 'Smith')
INSERT INTO CLASSROOM (trainerFName, trainerLName) VALUES ('Gemma', 'Taylor')
INSERT INTO TRAINEE (firstName, lastName, classId) VALUES ('Ryan', 'Newton', '1')
INSERT INTO TRAINEE (firstName, lastName, classId) VALUES ('Harry', 'Thompson', '2')
INSERT INTO TRAINEE (firstName, lastName, classId) VALUES ('Sophie', 'Attwell', '3')
